var quotables = [
'Always remember that you are unique , just like everyone else.'									 ,
'Honk if you love peace and quiet.'																	 ,
'If you can remain calm , you just do not have all the facts.'										 ,
'If you can not join `em , beat `em.'																 ,
'It is much easier to apologize than to ask permission.'											 ,
'The trouble with being in the rat race is that even if you win , you are still a rat.'				 ,
'There are two rules for ultimate success in life. Never tell everything you know.'					 ,
'98.23 percent of all statistics are made up on the spot.'											 ,
'99 percent of lawyers give the rest a bad name.'													 ,
'A conclusion is the place where you got tired of thinking.'										 ,
'A day without sunshine is like , well , night.'													 ,
'For every action , there is an equal and opposite criticism.'										 ,
'Give a man a fish ; he will eat for a day ; teach a man to fish ; he will sit in a boat all day drinking beer.' ,
'Half the people you know are below average.'														 ,
'Never put off until tomorrow what you can avoid doing altogether.'									 ,
'Pardon my driving; I am reloading.'																 ,
'Plan to be spontaneous tomorrow.'																	 ,
'War does not determine who is right , just who is left.'											 ,
'Whatever does not make you stronger , kills you.'													 ,
'A clear conscience is usually the sign of a bad memory.'											 ,
'A fine is a tax for doing wrong. A tax is a fine for doing well.'									 ,
'A waste is a terrible thing to mind.'																 ,
'Always try to be modest... and proud of it!'														 ,
'As long as there are tests , there will be prayer in public schools.'								 ,
'Back up my hard drive? How do I put it in reverse?'												 ,
'Bills travel through the mail at twice the speed of checks.'										 ,
'Borrow money from pessimists - they do not expect it back.'										 ,
'Change is inevitable , except from a vending machine.'												 ,
'Despite the cost of living , have you noticed how it remains so popular?'							 ,
'Do not feed the hand that bites you.'																 ,
'Do not make a molehill out of a mountain.'															 ,
'Do not use a little when a lot will do.'															 ,
'Eagles may soar , but weasels are not sucked into jet engines.'									 ,
'Every silver lining has a cloud.'																	 ,
'Every thorn has its rose'																			 ,
'Everybody repeat after me , We are all individuals.'												 ,
'Everyone has a photographic memory. Some do not have film.'										 ,
'Everyone has a right to be stupid. Some just abuse the privilege.'									 ,
'Experience is something that you do not get until just after you need it.'							 ,
'Flashlight: A case for holding dead batteries.'													 ,
'From great things come small beginnings.'															 ,
'Give them a mile and they will take a inch.'														 ,
'He who hesitates is probably right.'																 ,
'He who is lost hesitates.'																			 ,
'He who laughs last , thinks slowest.'																 ,
'He is not dead - he is electroencephalographically challenged.'									 ,
'How many of you believe in telekinesis? Raise my hands.'											 ,
'I almost had a psychic girlfriend but she left me before we met.'									 ,
'I feel like I am diagonally parked in a parallel universe.'										 ,
'I just got lost in thought. It was unfamiliar territory.'											 ,
'I started out with nothing , and I still have most of it.'											 ,
'I wished the buck stopped here , because I could sure use a few.'									 ,
'I wonder how much deeper the ocean would be without sponges.'										 ,
'If at first you do not succeed , destroy all evidence that you tried.'								 ,
'If the shoe fits , get another one just like it.'													 ,
'If you must choose between two evils , pick the one you have never tried before.'					 ,
'If you think nobody cares about you , try missing a couple of loan repayments.'					 ,
'It is hard to understand how a cemetery raised its burial costs and blamed it on the high cost of living.' ,
'It is said that if you line up all the cars in the world end to end , someone would still try to pass them.' ,
'It was recently discovered that research causes cancer in rats.'									 ,
'It is frustrating when you know all the answers , but nobody bothers to ask you the questions.'	 ,
'It is over till it is not over.'																	 ,
'Last guys finish nice.'																			 ,
'Light travels faster than sound. This is why some people appear bright until you hear them speak.'	 ,
'Living off the land of the fat.'																	 ,
'Madness takes its toll. Please have exact change.'													 ,
'Man waits for no time.'																			 ,
'Monday is an awful way to spend one-seventh of your life.'											 ,
'Never do card tricks for the group you play poker with.'											 ,
'No one is listening until you make a mistake.'														 ,
'Nothing is foolproof to a sufficiently talented fool.'												 ,
'On the keyboard of life , always keep one finger on the escape key.'								 ,
'On the other hand , you have different fingers.'													 ,
'Out with the new , in with the old.'																 ,
'Seen it all , done it all , can not remember most of it.'											 ,
'She is always late. Her ancestors arrived on the Juneflower.'										 ,
'Shin: A device for finding furniture.'																 ,
'Success always occurs in private , and failure in full view.'										 ,
'Take a short walk on a long pier.'																	 ,
'The 50-50-90 rule: Anytime you have a 50-50 chance of getting something right , there is a 90% probability you will get it wrong.' ,
'The hardness of the butter is proportional to the softness of the bread.'							 ,
'The latest survey shows that 3 out of 4 people make up 75% of the worlds population.'				 ,
'The problem with the gene pool is that there is no lifeguard.'										 ,
'The severity of the itch is proportional to the reach.'											 ,
'The sooner you fall behind , the more time you will have for catching up.'							 ,
'The storm before the quiet.'																		 ,
'The things that come to those who wait may be the things left by those who got there first.'		 ,
'The world makes money go round.'																	 ,
'There is a crowd in every one.'																	 ,
'Those who live by the sword get shot by those who do not.'											 ,
'To steal ideas from one person is plagiarism; to steal from many is research.'						 ,
'To succeed in politics , it is often necessary to rise above your principles.'						 ,
'Two rights do not make it a wrong.'																 ,
'Two wrongs are only the beginning.'																 ,
'What you get is what you see.'																		 ,
'When it pours it rains.'																			 ,
'When the chips are down , the buffalo is empty.'													 ,
'You can hide , but you can not run.'																 ,
'You can not have everything - where would you put it?'												 ,
'You can not judge a cover by its book.'															 ,
'You have the right to remain silent. Anything you say will be misquoted , then used against you.'	 ,
'You only love the one you hurt.'																	 ,
''];